url_mapping={
    "Dashboard":"https://bakingo.resoee.com/console2/dashboard",
    "Ops Dashboard":"https://bakingo.resoee.com/console2/dashboard",
    "AI Dashboard":"https://bakingo.resoee.com/console2/ai-dashboard",
    "Stock Dashboard":"https://bakingo.resoee.com/console2/asset-dashboard",
    "Process Flow":"https://bakingo.resoee.com/console2/process-flow",
    "Product Traceability":"https://bakingo.resoee.com/console2/order/tracking",
    "My Users Access":"https://bakingo.resoee.com/console2/account/access/user",
    "Modules Configuration":"https://bakingo.resoee.com/console2/account/modules/confriguration",
    "My Licenses":"https://bakingo.resoee.com/console2/account/my-licenses",
    "Wastage Reasons":"https://bakingo.resoee.com/console2/account/wastage/reasons",
    "My Audits":"https://bakingo.resoee.com/console2/account/my-audits",
    "My Machines":"https://bakingo.resoee.com/console2/account/my-machines",
    "My Containers":"https://bakingo.resoee.com/console2/account/my-containers",
    "Process Config":"https://bakingo.resoee.com/console2/process-config",
    "Subscriptions History":"https://bakingo.resoee.com/console2/analytics/my-subscriptions/history?clear=true",
    "AI Accuracies":"https://bakingo.resoee.com/console2/ai-workflow/accuracies",
    "AI Model Creation":"https://bakingo.resoee.com/console2/ai-workflow/ai-model",
    "Asset Types":"https://bakingo.resoee.com/console2/asset/asset-category",
    "Asset Monitoring":"https://bakingo.resoee.com/console2/asset/asset-monitoring",
    "Immovable Asset":"https://bakingo.resoee.com/console2/asset/asset-immovable",
    "Packaging Capacity":"https://bakingo.resoee.com/console2/asset/capacity",
    "My Franchise":"https://bakingo.resoee.com/console2/analytics/my-franchisee",
    "Request Refunds":"https://bakingo.resoee.com/console2/refunds/request",
    "Approve Refunds":"https://bakingo.resoee.com/console2/refunds/approve",
    "Refunds History":"https://bakingo.resoee.com/console2/refunds/history",
    "Temperature Images":"https://bakingo.resoee.com/console2/analytics/temperature/images",
    "Bills":"https://bakingo.resoee.com/console2/analytics/po/bill",
    "Bills Summary":"https://bakingo.resoee.com/console2/analytics/po/vendor/bills/summary",
    "Payment made":"https://bakingo.resoee.com/console2/analytics/po/payment/made",
    "Debit/Credit Note":"https://bakingo.resoee.com/console2/analytics/po/credits",
    "Ad-Hoc Expense/Income":"https://bakingo.resoee.com/console2/financial/petty",
    "Utilities":"https://bakingo.resoee.com/console2/financial/utilities",
    "Upload Data":"https://bakingo.resoee.com/console2/upload/template",
    "Generate E-Way Bill":"https://bakingo.resoee.com/console2/analytics/po/EWayBill/generate",
    "Create Order":"https://bakingo.resoee.com/console2/analytics/po/create",
    "Internal Store Sale Orders":"https://bakingo.resoee.com/console2/analytics/inventory/list/po",
    "Delivery Challan":"https://bakingo.resoee.com/console2/analytics/po/delivery/challan",
    "Vendor Orders":"https://bakingo.resoee.com/console2/analytics/list/vendor/orders",
    "Asset Purchase Order":"https://bakingo.resoee.com/console2/analytics/list/capex/vendor/orders",
    "GRN Listing":"https://bakingo.resoee.com/console2/analytics/list/grn",
    "Assets Quote":"https://bakingo.resoee.com/console2/analytics/list/quote",
    "Internal Purchase Orders":"https://bakingo.resoee.com/console2/analytics/internal/po/list",
    "Asset Transfer Order":"https://bakingo.resoee.com/console2/analytics/list/asset/store",
    "Store Bills":"https://bakingo.resoee.com/console2/analytics/po/internal/bill",
    "Orders History":"https://bakingo.resoee.com/console2/analytics/order/history/list",
    "Buyers Sales Orders":"https://bakingo.resoee.com/console2/analytics/list/buyer/orders",
    "FMS Orders List":"https://bakingo.resoee.com/console2/analytics/list/fms",
    "Production Plans":"https://bakingo.resoee.com/console2/analytics/productionPlans",
    "Indent List":"https://bakingo.resoee.com/console2/analytics/inventory/list/indent",
    "Custom Reports":"https://bakingo.resoee.com/console2/inventory-reports",
    "COGS History":"https://bakingo.resoee.com/console2/analytics/cogs/history/list?clear=true",
    "Product Cost Analysis":"https://bakingo.resoee.com/console2/analytics/bom/summary",
    "Production Cost History":"https://bakingo.resoee.com/console2/analytics/bom/history/list?clear=true",
    "Inventory Analysis":"https://bakingo.resoee.com/console2/analytics/stock/summary",
    "Inventory Analysis History":"https://bakingo.resoee.com/console2/analytics/stock/history/list?clear=true",
    "Day End Report":"https://bakingo.resoee.com/console2/dayendreport",
    "Transit Loss Analysis":"https://bakingo.resoee.com/console2/analytics/transit/summary",
    "Transit Loss Analysis History":"https://bakingo.resoee.com/console2/analytics/transit/history/list?clear=true",
    "Forecasting Analysis":"https://bakingo.resoee.com/console2/analytics/forecasting/summary",
    "Forecasting Analysis List":"https://bakingo.resoee.com/console2/analytics/forecasting/analysis/list",
    "Variance Analysis":"https://bakingo.resoee.com/console2/analytics/audit/summary",
    "Variance History":"https://bakingo.resoee.com/console2/analytics/audit/history/list?clear=true",
    "AI GRN History":"https://bakingo.resoee.com/console2/analytics/ai/grn/history",
    "AI GRN Images":"https://bakingo.resoee.com/console2/analytics/ai/grn/images",
    "Stock Consumption":"https://bakingo.resoee.com/console2/analytics/inventory/consumption/stock",
    "Cooking History":"https://bakingo.resoee.com/console2/analytics/cooking/analysis/list?",
    "Ingredients Images":"https://bakingo.resoee.com/console2/analytics/cooking/images",
    "Production History":"https://bakingo.resoee.com/console2/analytics/production/history",
    "Production Images":"https://bakingo.resoee.com/console2/analytics/production/images",
    "Wastage History":"https://bakingo.resoee.com/console2/analytics/wastage/history/list?clear=true",
    "Wastage Images":"https://bakingo.resoee.com/console2/analytics/wastage/images",
    "Wastage Components":"https://bakingo.resoee.com/console2/analytics/wastage/components",
    "Quality Analysis":"https://bakingo.resoee.com/console2/analytics/quality/analysis?clear=true",
    "Quality History":"https://bakingo.resoee.com/console2/analytics/quality/history/list?clear=true",
    "Nutrition Analysis":"https://bakingo.resoee.com/console2/analytics/quality/nutrition",
    "Current Stock":"https://bakingo.resoee.com/console2/analytics/inventory/sku-report",
    "Stock History":"https://bakingo.resoee.com/console2/analytics/inventory/stock",
    "Inventory Summary":"https://bakingo.resoee.com/console2/analytics/inventory/summary",
    "Inventory Analysis":"https://bakingo.resoee.com/console2/analytics/inventory/analysis?clear=true",
    "AI Filling/Packaging Summary":"https://bakingo.resoee.com/console2/ai_packaging",
    "AI Filling/Packaging History":"https://bakingo.resoee.com/console2/analytics/cooking/analysis/list?",
    "AI Dispatch History":"https://bakingo.resoee.com/console2/analytics/ai/dispatch/history",
    "AI Dispatch Images":"https://bakingo.resoee.com/console2/analytics/ai/dispatch/images",
    "Brand Trends":"https://bakingo.resoee.com/console2/analytics/brand-trends",
    "Orders History":"https://bakingo.resoee.com/console2/analytics/brand-trends",
    "Feature Images":"https://bakingo.resoee.com/console2/analytics/feature/images",
    "Temperature Digit Images":"https://bakingo.resoee.com/console2/analytics/temperature/digit/images",
    "App Outwarding Images":"https://bakingo.resoee.com/console2/analytics/app/outwarding/images",
    "My Customers":"https://bakingo.resoee.com/console2/analytics/my-customers",
    "Store Settings":"https://bakingo.resoee.com/console2/outlets/settings",
    "Stores":"https://bakingo.resoee.com/console2/outlets/stores",
    "Riders":"https://bakingo.resoee.com/console2/outlets/riders",
    "Printer Config":"https://bakingo.resoee.com/console2/outlets/printer-config",
    "Live View":"https://bakingo.resoee.com/console2/outlets/live",
    "Holiday":"https://bakingo.resoee.com/console2/outlets/holiday",
    "My Brands":"https://bakingo.resoee.com/console2/brands",
    "Active Products":"https://bakingo.resoee.com/console2/products/active",
    "All Products":"https://bakingo.resoee.com/console2/products/all",
    "Customization":"https://bakingo.resoee.com/console2/products/customizations",
    "Variants":"https://bakingo.resoee.com/console2/products/threshold/variants",
    "Product Category":"https://bakingo.resoee.com/console2/products/category",
    "Product Sub-Category":"https://bakingo.resoee.com/console2/products/sub/category",
    "Combos":"https://bakingo.resoee.com/console2/products/combos",
    "Nutritional info":"https://bakingo.resoee.com/console2/products/nutritional-info",
    "Bulk Ordering":"https://bakingo.resoee.com/console2/products/bulk",
    "Subscription":"https://bakingo.resoee.com/console2/products/subscription",
    "Master Menu":"https://bakingo.resoee.com/console2/menus/master",
    "Quality Settings":"https://bakingo.resoee.com/console2/kitchen/quality/setting",
    "Quality Config":"https://bakingo.resoee.com/console2/kitchen/quality/config",
    "Live QC":"https://bakingo.resoee.com/console2/kitchen/quality/live",
    "Cooking Settings":"https://bakingo.resoee.com/console2/kitchen/cooking/setting",
    "Recipe":"https://bakingo.resoee.com/console2/kitchen/cooking/recipe",
    "Cooking Config":"https://bakingo.resoee.com/console2/kitchen/cooking/recipe",
    "Inventory Config":"https://bakingo.resoee.com/console2/kitchen/inventory/config",
    "Vendors List":"https://bakingo.resoee.com/console2/vendors",
    "Vendor Contract":"https://bakingo.resoee.com/console2/vendor/contract",
    "Buyers List":"https://bakingo.resoee.com/console2/buyers",
    "Buyers Contract":"https://bakingo.resoee.com/console2/buyer/contract",
    "Product Mapping":"https://bakingo.resoee.com/console2/product-process-map",
    "Features":"https://bakingo.resoee.com/console2/kitchen/features",
    "Left Over Inventory List":"https://bakingo.resoee.com/console2/left-over-inventory/process",
    "Left Over Inventory History Scans":"https://bakingo.resoee.com/console2/left-over-inventory/history",
    "Wastage Inventory":"https://bakingo.resoee.com/console2/wastage",
    "Similar Products Mapping":"https://bakingo.resoee.com/console2/similar-products-mapping",
    "Regions Mapping":"https://bakingo.resoee.com/console2/regions-mapping",
    "Label Generator":"https://bakingo.resoee.com/console2/label/generator/list",
    "Shift Management":"https://bakingo.resoee.com/console2/label/generator/list"
}